query USER_EXISTS($email: String!, $phone: String!) {
  userExists(email: $email, phone: $phone)
}

query RECOVERY_PASSWORD($email: String!) {
  getRecoveryEmail(email: $email)
}

query UPDATE_PASSWORD($recoveryId: String!, $password: String!) {
  updatePassword(recoveryId: $recoveryId, password: $password)
}

query GET_FREE_PROPERTY {
  properties(where: { owner: null }) {
    id
    name
    owner {
      email
    }
  }
}

mutation ASSIGN_OWNER($pId: ID!, $data: PropertyUpdateInput!) {
  updateProperty(where: { id: $pId }, data: $data) {
    id
  }
}

query VERIFY_PHONE($code: String!) {
  verifyPhone(code: $code)
}

query PHONE_VERIFIED {
  phoneVerified
}

query IS_LOGGED {
  authenticatedItem {
    ... on User {
      id
      isAdmin
      needsBill
      name
      isVerified
      rfc {
        publicUrl
      }
      avatar {
        publicUrl
      }
    }
  }
}

query GENERATE_PAYMENTS {
  generatePayments {
    id
  }
}

mutation LOG_IN($email: String!, $password: String!) {
  authenticateUserWithPassword(email: $email, password: $password) {
    ... on UserAuthenticationWithPasswordSuccess {
      sessionToken
      item {
        properties {
          square
          lot
        }
      }
    }
    ... on UserAuthenticationWithPasswordFailure {
      message
    }
  }
}

query IS_USER($email: String!, $phone: String) {
  isUser(email: $email, phone: $phone)
}

mutation UPDATE_PAYMENT($pId: ID!, $image: Upload) {
  updatePayment(where: { id: $pId }, data: { status: pending, image: $image }) {
    id
    status
  }
}

mutation TEMP_CREATE_USER($email: String!, $password: String!, $phone: String) {
  createUser(
    data: {
      email: $email
      password: $password
      name: "Predefinido"
      phone: $phone
      isVerified: true
    }
  ) {
    name
  }
}
mutation CREATE_USER(
  $name: String!
  $phone: String!
  $email: String!
  $password: String!
  $properties: [PropertyCreateInput!]
) {
  createUser(
    data: {
      name: $name
      phone: $phone
      email: $email
      password: $password
      properties: { create: $properties }
    }
  ) {
    name
  }
}

query GET_PAYMENTS($id: ID!) {
  user(where: { id: $id }) {
    properties {
      id
      square
      lot
      name
      payments {
        id
        dueAt
        status
        bill {
          factura {
            publicUrl
          }
        }
        dueAmount
        image {
          publicUrl
          publicUrlTransformed(transformation: { width: "300" })
          mimetype
        }
      }
    }
  }
}

mutation LOG_OUT {
  endSession
}
