query GET_PAYMENTS($initialDate: DateTime!, $finalDate: DateTime!) {
  payments(
    where: {
      AND: [{ dueAt: { lte: $finalDate } }, { dueAt: { gte: $initialDate } }]
    }
  ) {
    property {
      owner {
        name
        phone
        email
        id
      }
      square
      lot
    }
    id
    createdAt
    dueAt
    status
    image {
      publicUrl
    }
  }
}

query PAYMENT_BY_USER($id: ID!) {
  user(where: { id: $id }) {
    properties {
      id
      payments {
        id
        status
        dueAmount
        image {
          publicUrl
        }
      }
    }
  }
}

mutation APROVE_PAYMENT($id: ID) {
  updatePayment(where: { id: $id }, data: { status: payed }) {
    status
    id
  }
}

mutation UPDATE_USER($id: ID!, $image: Upload) {
  updateUser(where: { id: $id }, data: { rfc: $image }) {
    rfc {
      publicUrl
    }
    needsBill
  }
}