query GET_TOTAL_VOTES($id: ID, $option: String, $option2: String) {
  option1: votesCount(
    where: { survey: { id: { equals: $id } }, vote: { equals: $option } }
  )
  option2: votesCount(
    where: { survey: { id: { equals: $id } }, vote: { equals: $option2 } }
  )
}
