mutation CREATE_PROPERTY(
  $lot: String!
  $square: String!
  $kindOfProperty: PropertyKindOfPropertyType!
) {
  createProperty(data: { lot: $lot, square: $square, kindOfProperty: $kindOfProperty }) {
    id
    square
  }
}

mutation CREATE_OWNER($data: UserCreateInput!) {
  createUser(data: $data) {
    name
  }
}

mutation UPDATE_OWNER($id: ID, $data: UserUpdateInput!) {
  updateUser(where: { id: $id }, data: $data) {
    name
  }
}

query GET_PROPERTIES {
  properties(where: { owner: null }, orderBy: { name: asc }) {
    name
    square
    lot
    id
    kindOfProperty
    owner {
      id
    }
    payments {
      id
    }
  }
}

query GET_OWNER($id: ID) {
  user(where: { id: $id }) {
    name
    email
    phone
    properties {
      id
    }
  }
}
