mutation CREATE_PROPERTY(
  $lot: String!
  $square: String!
  $kindOfProperty: PropertyKindOfPropertyType!
) {
  createProperty(data: { lot: $lot, square: $square, kindOfProperty: $kindOfProperty }) {
    id
    square
  }
}
