mutation CREATE_PROPERTY(
  $lot: String!
  $square: String!
  $kindOfProperty: PropertyKindOfPropertyType!
) {
  createProperty(data: { lot: $lot, square: $square, kindOfProperty: $kindOfProperty }) {
    id
    square
  }
}

mutation CREATE_OWNER(
  $name: String!
  $email: String!
  $password: String!
  $phone: String
  $properties: ID
) {
  createUser(
    data: {
      email: $email
      password: $password
      name: $name
      phone: $phone
      isVerified: true
      isOwner: true
      properties: { connect: { id: $properties } }
    }
  ) {
    name
  }
}
